### ISSUE TITLE
Accept Google Application Default Credentials

### ISSUE THREAD

**Issue by rubensf** [codeonline-io/falco-gke-audit-bridge#19]
Currently, the only way to authenticate is exporting [a service account key](https://github.com/opsgy/falco-gke-audit-bridge/blob/master/src/audit.service.ts#L26-L33). GKE can work with identity federation, bypassing the need to export risky Service Account credentials.

We could enhance this example to also accept that, for simplicity. This can be easily achieved with a couple steps:

1. Add some terraform code for WIF [here](https://github.com/opsgy/falco-gke-audit-bridge/blob/master/deploy/terraform/audit-pubsub.tf#L63-L66)

```
resource "google_service_account_iam_binding" "k8s_bindings" {
  project.           = var.project_id
  service_account_id = ${var.name}"
  role               = "roles/iam.workloadIdentityUser"
  members = [
    "serviceAccount:${var.project_id}.svc.id.goog[${var.k8s_namespace}/${var.name}]",
  ]
}
```

2. Add a K8S service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-k8s-audit
  namespace: falco
  annotations:
    iam.gke.io/gcp-service-account: falco-k8s-audit@${project}.iam.gserviceaccount.com
```

3. Use it in the deployment
```
spec:
      serviceAccountName: falco-k8s-audit
```

4. Change the [code here](https://github.com/opsgy/falco-gke-audit-bridge/blob/master/src/audit.service.ts#L26-L33) to use the `google-auth-library` ([guide here](https://www.npmjs.com/package/google-auth-library#choosing-the-correct-credential-type-automatically))
```
  const auth = new GoogleAuth({
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
  });
  const client = await auth.getClient();
  const projectId = await auth.getProjectId();
```
